apiVersion: v1
kind: ConfigMap
metadata:
  name: vantage6-store-config
  namespace: vantage6-server
data:
  config.yaml: |
    allow_drop_all: 'True'
    api_path: /store
    description: 'Vantage store version 5'
    ip: 0.0.0.0
    logging:
      backup_count: 5
      datefmt: '%Y-%m-%d %H:%M:%S'
      file: k8s.log
      format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
      level: {{ .Values.store.logging.level }}
      loggers:
      - level: warning
        name: urllib3
      - level: warning
        name: socketIO-client
      - level: warning
        name: socketio.server
      - level: warning
        name: engineio.server
      - level: warning
        name: sqlalchemy.engine
      - level: warning
        name: requests_oauthlib.oauth2_session
      max_size: 1024
      use_console: true
    policies:
      algorithm_view: public
      allow_localhost: false
    port: '7602'
    root_user:
      username: root
      v6_server_uri: http://vantage6-server-backend-service/api
    uri: postgresql://vantage6user:vantage6password@store-postgres-service:5432/store