apiVersion: v2
name: auth
description: A Helm chart to deploy a keycloak server to authenticate vantage6 users and nodes
type: application
version: "5.0.0-a38"
appVersion: "5.0.0-a38"
dependencies:
  - name: keycloak
    version: "24.6.1"
    repository: oci://registry-1.docker.io/bitnamicharts
