{{- if .Values.prometheus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
{{ include "vantage6.labels" . | indent 4 }}
    component: prometheus
spec:
  selector:
    matchLabels:
{{ include "vantage6.matchLabels" . | indent 6 }}
      component: prometheus

  template:
    metadata:
      labels:
{{ include "vantage6.labels" . | indent 8 }}
        component: prometheus
    spec:
      # initialize by making the volume writable inside the container
      initContainers:
      - name: volume-permissions
        image: busybox:latest
        command: ["sh", "-c"]
        args:
          - chmod -R 777 /prometheus
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: prometheus-data
          mountPath: /prometheus
      # run the prometheus container
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image | default "prom/prometheus:latest" }}
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: {{ .Release.Name }}-prom-conf
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-prom-pvc
{{- end }}
