apiVersion: v2
name: server
description: A Helm chart for deploying the vantage6 server
type: application
version: "5.0.0-a47"
appVersion: "5.0.0-a47"
dependencies:
  - name: common
    version: "5.0.0-a47"
    repository: file://../common
