{{- if not .Values.database.external }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-kc-pgres-pvc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.database.storageClass | default "local-storage" }}
  selector:
    matchLabels:
      type: local
      app: keycloak
{{- end }}
