apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vantage6-server-service
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
{{ include "vantage6.matchLabels" . | indent 4 }}
    component: vantage6-server
  ports:
    - protocol: TCP
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.internal.port }}
      name: vantage6-server-backend
{{- if and .Values.server.dev.forward_ports .Values.server.dev.local_port_to_expose }}
      nodePort: {{ .Values.server.dev.local_port_to_expose }}
{{- end }}
{{- if and .Values.prometheus .Values.prometheus.enabled }}
    - protocol: TCP
      port: {{ .Values.prometheus.exporter_port | default 7603 }}
      targetPort: {{ .Values.prometheus.exporter_port | default 7603 }}
      name: prometheus-exporter
  {{- if and .Values.server.dev.forward_ports .Values.server.dev.local_prometheus_port_to_expose }}
      nodePort: {{ .Values.server.dev.local_prometheus_port_to_expose }}
  {{- end }}
{{- end }}
{{- if and .Values.server.dev.forward_ports .Values.server.dev.local_port_to_expose }}
  type: NodePort
{{- else }}
  type: ClusterIP
{{- end }}
{{- if gt (int .Values.server.replications) 1 }}
  sessionAffinity: ClientIP # does not work in wsl
{{- end }}