apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}-kc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
{{ include "auth.labels" . | indent 4 }}
spec:
  instances: {{ .Values.keycloak.instances }}
  {{- if .Values.keycloak.hostname }}
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
  {{- else if not .Values.keycloak.production }}
  hostname:
    strict: false
  {{- end }}
  db:
    vendor: postgres
    {{- if .Values.database.external }}
    host: {{ .Values.database.host }}
    {{- else }}
    host: {{ .Release.Name }}-kc-pgres
    {{- end }}
    {{- if .Values.database.port }}
    port: {{ .Values.database.port }}
    {{- end }}
    database: {{ .Values.database.name }}
    usernameSecret:
      name: {{ .Release.Name }}-kc-db-secret
      key: username
    passwordSecret:
      name: {{ .Release.Name }}-kc-db-secret
      key: password
  {{- if .Values.keycloak.production }}
  http:
    httpEnabled: false
    httpsPort: 8443
    {{- if .Values.keycloak.tls.enabled }}
      {{- if .Values.keycloak.tls.autoGenerated }}
    # TLS will be auto-generated by the operator
      {{- else if .Values.keycloak.tls.secretName }}
    tlsSecret: {{ .Values.keycloak.tls.secretName }}
      {{- end }}
    {{- end }}
  {{- else }}
  http:
    httpEnabled: true
    httpPort: 8080
  {{- end }}
  {{- if .Values.keycloak.resources }}
  resources:
    {{- if .Values.keycloak.resources.requests }}
    requests:
      {{- if .Values.keycloak.resources.requests.memory }}
      memory: {{ .Values.keycloak.resources.requests.memory }}
      {{- end }}
      {{- if .Values.keycloak.resources.requests.cpu }}
      cpu: {{ .Values.keycloak.resources.requests.cpu }}
      {{- end }}
    {{- end }}
    {{- if .Values.keycloak.resources.limits }}
    limits:
      {{- if .Values.keycloak.resources.limits.memory }}
      memory: {{ .Values.keycloak.resources.limits.memory }}
      {{- end }}
      {{- if .Values.keycloak.resources.limits.cpu }}
      cpu: {{ .Values.keycloak.resources.limits.cpu }}
      {{- end }}
    {{- end }}
  {{- end }}
  # Bootstrap admin credentials - used for initial Keycloak admin user creation
  # If not specified, the operator will generate random credentials and store them
  # in a secret named <keycloak-cr-name>-initial-admin which is inconvenient.
  {{- $keycloakAdminExistingSecret := .Values.keycloak.auth.adminUserSecret | default "" }}
  {{- $hasExistingKCAdminSecret := ne (trim $keycloakAdminExistingSecret) "" }}
  {{- $keycloakAdminSecretName := ($keycloakAdminExistingSecret | default (printf "%s-kc-adm-secret" .Release.Name)) }}
  bootstrapAdmin:
    user:
      secret: {{ $keycloakAdminSecretName }}
