apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}-kc
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
{{ include "auth.labels" . | indent 4 }}
spec:
  instances: {{ .Values.keycloak.instances }}
  {{- if .Values.keycloak.hostname.hostname }}
  hostname:
    hostname: {{ .Values.keycloak.hostname.hostname }}
  {{- else if not .Values.keycloak.production }}
  hostname:
    strict: false
  {{- end }}
  db:
    vendor: postgres
    {{- if .Values.database.external }}
    host: {{ .Values.keycloak.database.host }}
    {{- else }}
    host: {{ .Release.Name }}-kc-pgres
    {{- end }}
    database: {{ .Values.keycloak.database.database }}
    usernameSecret:
      name: {{ .Release.Name }}-kc-db-secret
      key: username
    passwordSecret:
      name: {{ .Release.Name }}-kc-db-secret
      key: password
  {{- if .Values.keycloak.production }}
  http:
    httpEnabled: false
    httpsPort: 8443
    {{- if .Values.keycloak.tls.enabled }}
      {{- if .Values.keycloak.tls.autoGenerated }}
    # TLS will be auto-generated by the operator
      {{- else if .Values.keycloak.tls.secretName }}
    tlsSecret: {{ .Values.keycloak.tls.secretName }}
      {{- end }}
    {{- end }}
  {{- else }}
  http:
    httpEnabled: true
    httpPort: 8080
  {{- end }}
  {{- if .Values.keycloak.resources }}
  resources:
    {{- if .Values.keycloak.resources.requests }}
    requests:
      {{- if .Values.keycloak.resources.requests.memory }}
      memory: {{ .Values.keycloak.resources.requests.memory }}
      {{- end }}
      {{- if .Values.keycloak.resources.requests.cpu }}
      cpu: {{ .Values.keycloak.resources.requests.cpu }}
      {{- end }}
    {{- end }}
    {{- if .Values.keycloak.resources.limits }}
    limits:
      {{- if .Values.keycloak.resources.limits.memory }}
      memory: {{ .Values.keycloak.resources.limits.memory }}
      {{- end }}
      {{- if .Values.keycloak.resources.limits.cpu }}
      cpu: {{ .Values.keycloak.resources.limits.cpu }}
      {{- end }}
    {{- end }}
  {{- end }}
  # Admin credentials are set via environment variables
  # The operator will use these to configure the admin user
  env:
    - name: KEYCLOAK_ADMIN
      value: {{ .Values.keycloak.auth.adminUser }}
    - name: KEYCLOAK_ADMIN_PASSWORD
      secret:
        name: {{ .Release.Name }}kc-adm-secret
        key: password
