{{- if and
    (eq (.Values.database.k8sNodeName | default "") "docker-desktop")
    (not (lookup "storage.k8s.io/v1" "StorageClass" "" "local-storage"))
}}
{{- if or
    (eq (.Values.hq.logging.storageClass | default "local-storage") "local-storage")
    (eq (.Values.prometheus.storageClass | default "local-storage") "local-storage")
    (not (.Values.database.external | default false))
}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}
{{- end }}
