applications:
  client:
    api_key: 
    server_url: http://localhost:5000
    server_entry_point: /api/token
    delay: 30 # seconds
    task_dir: tasks
    docker_host: 127.0.0.1
    database_uri: ''

    logging:
        level:        DEBUG                  # Can be on of 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
        file:         logs/client.log       # Filename of logfile
        use_console:  True                   # Log output to the console?
        backup_count: 5                      # Number of logs to keep
        max_size:     1024                   # Specified in kB (i.e. 1024 means a maximum file size of 1MB)
        format:       "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
        # datefmt:      "%Y-%m-%d %H:%M:%S"
        datefmt:      "%H:%M:%S"