allow_drop_all: true
api_path: ''
description: docker
ip: 0.0.0.0
logging:
  backup_count: 5
  datefmt: '%Y-%m-%d %H:%M:%S'
  file: docker.log
  format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
  level: DEBUG
  max_size: 1024
  use_console: true
port: '7601'
uri: postgresql://postgres:changeme@database