apiVersion: v2
name: hq
description: A Helm chart for deploying the vantage6 headquarters
type: application
version: "5.0.0-b1"
appVersion: "5.0.0-b1"
dependencies:
  - name: common
    version: "5.0.0-b1"
    repository: file://../common
