apiVersion: v2
name: store
description: A Helm chart to deploy a vantage6 algorithm store
type: application
version: "5.0.0-b1"
appVersion: "5.0.0-b1"
dependencies:
  - name: common
    version: "5.0.0-b1"
    repository: file://../common
