store:
  replications: 1
  description: Vantage algorithm store version 5
  api_path: /store

  keycloakUrl: http://vantage6-auth.vantage6.svc.cluster.local
  keycloakRealm: vantage6
  keycloakAdminUsername: admin
  keycloakAdminPassword: admin
  keycloakAdminClient: backend-admin-client
  keycloakAdminClientSecret: myadminclientsecret
  vantage6ServerUri: http://localhost:7601/server

  policies:
    algorithmView: public

  dev:
    host_uri: host.docker.internal
    disable_review: false
    review_own_algorithm: false
    forward_ports: true

  image: harbor2.vantage6.ai/infrastructure/store:latest

  internal:
    port: 7602
  port: 7602

  logging:
    level: DEBUG
    file: store.log
    max_size: 1024
    use_console: true
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
    storageSize: "128M"
    storageClass: "local-storage"
    volumeHostPath: "/var/log/vantage6-store"
    backup_count: 5
    loggers:
    - level: warning
      name: urllib3
    - level: warning
      name: socketIO-client
    - level: warning
      name: socketio.server
    - level: warning
      name: engineio.server
    - level: warning
      name: sqlalchemy.engine

database:
  external: false

  image:
    repository: postgres
    tag: 13

  username: vantage6
  password: vantage6
  name: vantage6

  volumePath: /mnt/data_store
  k8sNodeName: docker-desktop