language: python
python:
  - 3.6
  - 3.7
  # - 3.8
  # - 3.8-dev

branches:
  - master
  - DEV
  - hotfix
  - /release/(.+)/

install:
  - pip install -e .[dev]

before_script:
  - source git-installs.sh

script:
  - coverage run --source=vantage6 --omit="utest.py" utest.py

after_success:
  - coveralls
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

# notifications:
#   webhooks: https://outlook.office.com/webhook/5ecba249-8938-44bf-b500-29bed1621b7f@a5e4637f-71f0-40bb-b540-aabca71204f3/TravisCI/7550616fdf6e42139d556367161f2595/c44ed181-5baa-48fd-a8ba-bdb24d542224
