apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
{{ include "vantage6.matchLabels" . | indent 4 }}
    component: vantage6-hq
  ports:
    - protocol: TCP
      port: {{ .Values.hq.port }}
      targetPort: {{ .Values.hq.internal.port }}
      name: vantage6-hq-backend
{{- if and .Values.hq.dev.forward_ports .Values.hq.dev.local_hub_port_to_expose }}
      nodePort: {{ .Values.hq.dev.local_hub_port_to_expose }}
{{- end }}
{{- if and .Values.prometheus .Values.prometheus.enabled }}
    - protocol: TCP
      port: {{ .Values.prometheus.exporter_port | default 7603 }}
      targetPort: {{ .Values.prometheus.exporter_port | default 7603 }}
      name: prometheus-exporter
  {{- if and .Values.hq.dev.forward_ports .Values.hq.dev.local_prometheus_port_to_expose }}
      nodePort: {{ .Values.hq.dev.local_prometheus_port_to_expose }}
  {{- end }}
{{- end }}
{{- if and .Values.hq.dev.forward_ports .Values.hq.dev.local_hub_port_to_expose }}
  type: NodePort
{{- else }}
  type: ClusterIP
{{- end }}
{{- if gt (int .Values.hq.replications) 1 }}
  sessionAffinity: ClientIP # does not work in wsl
{{- end }}